### ISSUE TITLE
rio pansharpen command fails with AttributeError: bilinear

### ISSUE THREAD

**Issue by rafaelalmeida** [mapbox/rio-pansharpen#23]
I am trying to get this to run, but every try I do ends up with this error. Stack trace follows:

`Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/envs/rasterio-env/bin/rio", line 11, in <module>
    sys.exit(main_group())
  File "/home/ubuntu/anaconda2/envs/rasterio-env/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/anaconda2/envs/rasterio-env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/anaconda2/envs/rasterio-env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/anaconda2/envs/rasterio-env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/anaconda2/envs/rasterio-env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/anaconda2/envs/rasterio-env/lib/python2.7/site-packages/rio_pansharpen/scripts/cli.py", line 46, in pansharpen
    jobs, half_window, customwindow
  File "/home/ubuntu/anaconda2/envs/rasterio-env/lib/python2.7/site-packages/rio_pansharpen/worker.py", line 167, in calculate_landsat_pansharpen
    rm.run(jobs)
  File "/home/ubuntu/anaconda2/envs/rasterio-env/lib/python2.7/site-packages/riomucho/__init__.py", line 108, in run
    for data, window in self.pool.imap_unordered(reader_worker, self.windows):
  File "/home/ubuntu/anaconda2/envs/rasterio-env/lib/python2.7/site-packages/riomucho/single_process_pool.py", line 9, in imap_unordered
    yield reader_worker(i)
  File "/home/ubuntu/anaconda2/envs/rasterio-env/lib/python2.7/site-packages/riomucho/__init__.py", line 33, in manualRead
    raise e
AttributeError: bilinear`

I am running this in a conda-env. This is the output of `conda env export` (untruncated since the cause may be some conflict):

`Using Anaconda Cloud api site https://api.anaconda.org
name: rasterio-env
dependencies:
- affine=2.0.0=py27_0
- click=6.6=py27_0
- click-plugins=1.0.3=py27_0
- cligj=0.4.0=py27_0
- curl=7.49.0=1
- enum34=1.1.6=py27_0
- geos=3.5.0=0
- geotiff=1.4.1=0
- hdf4=4.2.12=0
- hdf5=1.8.17=1
- jbig=2.1=0
- jpeg=8d=1
- kealib=1.4.6=0
- libgdal=2.1.0=0
- libnetcdf=4.4.1=0
- libtiff=4.0.6=2
- menpo::opencv3=3.1.0=py27_0
- mkl=11.3.3=0
- numpy=1.11.1=py27_0
- openssl=1.0.2h=1
- pip=8.1.2=py27_0
- proj4=4.9.2=0
- pyparsing=2.1.4=py27_0
- python=2.7.12=1
- rasterio=0.36.0=np111py27_0
- readline=6.2=2
- setuptools=25.1.6=py27_0
- snuggs=1.4.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- xerces-c=3.1.4=0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - boto==2.39.0
  - cycler==0.10.0
  - dask==0.11.0
  - decorator==4.0.10
  - futures==3.0.5
  - geocoder==1.9.0
  - geojson==1.3.3
  - homura==0.1.3
  - humanize==0.5.1
  - landsat-util==0.13.0
  - matplotlib==1.5.1
  - networkx==1.11
  - pandas==0.18.1
  - pillow==3.3.1
  - polyline==1.1
  - pycurl==7.43.0
  - pymongo==3.3.0
  - pyproj==1.9.5.1
  - python-dateutil==2.5.1
  - pytz==2016.6.1
  - ratelim==0.1.6
  - requests==2.7.0
  - requests-futures==0.9.7
  - rio-mucho==0.2.1
  - rio-pansharpen==0.2.0.dev1
  - scikit-image==0.12.3
  - scipy==0.17.0
  - shapely==1.5.16
  - six==1.8.0
  - termcolor==1.1.0
  - toolz==0.8.0
  - usgs==0.1.9
prefix: /home/ubuntu/anaconda2/envs/rasterio-env`

**Comment by rafaelalmeida** [comment]
Despite what Anaconda says, I seemed to have rasterio 0.32 instead of 0.32 installed. The above pull request makes the dependency on >= 0.35 explicit.

**Comment by perrygeo** [comment]
fixes in #24
