### ISSUE TITLE
ValueError: blockxsize exceeds raster width with 

### ISSUE THREAD

**Issue by rafaelalmeida** [mapbox/rio-pansharpen#25]
Not sure if this is a problem with rio-pansharpen itself or rio-mucho.

I tried running the pansharpening over cropped Landsat images, but a particular window size keeps giving me this error, no matter if I try running from Python or directly via `rio pansharpen`.

After some tests, I managed to create the following repeatable sequence of actions to reproduce the problem:

1) Download some arbitrary Landsat scene. In my tests, any scene will cause the same problem.

    landsat download -b 8,4,3,2 LC80390282016240LGN00

2) Crop the scene using `gdal_translate` to this exact window:

```
gdal_translate -srcwin 3812 2460 366 740 /home/ubuntu/landsat/downloads/LC82220762016210LGN00/LC82220762016210LGN00_B8.TIF gdal_b8.tif

gdal_translate -srcwin 1906 1230 183 371 /home/ubuntu/landsat/downloads/LC82220762016210LGN00/LC82220762016210LGN00_B4.TIF gdal_b4.tif

gdal_translate -srcwin 1906 1230 183 371 /home/ubuntu/landsat/downloads/LC82220762016210LGN00/LC82220762016210LGN00_B3.TIF gdal_b3.tif

gdal_translate -srcwin 1906 1230 183 371 /home/ubuntu/landsat/downloads/LC82220762016210LGN00/LC82220762016210LGN00_B2.TIF gdal_b2.tif
```

3) Run the pansharpening:

`rio pansharpen gdal_b{8,4,3,2}.tif pan.tif`

The full output is as follows:

```
/home/ubuntu/anaconda2/envs/benchmark/lib/python2.7/site-packages/rio_pansharpen/scripts/cli.py:46: FutureWarning: The value of this property will change in version 1.0. Please see https://github.com/mapbox/rasterio/issues/86 for details.
  jobs, half_window, customwindow
/home/ubuntu/anaconda2/envs/benchmark/lib/python2.7/site-packages/rio_pansharpen/worker.py:134: FutureWarning: GDAL-style transforms are deprecated and will not be supported in Rasterio 1.0.
  transform=guard_transform(pan_src.transform),
/home/ubuntu/anaconda2/envs/benchmark/lib/python2.7/site-packages/rio_pansharpen/worker.py:160: FutureWarning: GDAL-style transforms are deprecated and will not be supported in Rasterio 1.0.
  "r_aff": guard_transform(r_meta['transform']),
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/envs/benchmark/lib/python2.7/site-packages/rio_pansharpen/worker.py", line 167, in calculate_landsat_pansharpen
    rm.run(jobs)
  File "/home/ubuntu/anaconda2/envs/benchmark/lib/python2.7/site-packages/riomucho/__init__.py", line 108, in run
    with rio.open(self.outpath, 'w', **self.options) as dst:
  File "/home/ubuntu/anaconda2/envs/benchmark/lib/python2.7/site-packages/rasterio/__init__.py", line 193, in open
    s.start()
  File "rasterio/_io.pyx", line 1401, in rasterio._io.RasterUpdater.start (rasterio/_io.c:19697)
ValueError: blockxsize exceeds raster width.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/envs/benchmark/bin/rio", line 11, in <module>
    sys.exit(main_group())
  File "/home/ubuntu/anaconda2/envs/benchmark/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/anaconda2/envs/benchmark/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/anaconda2/envs/benchmark/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/anaconda2/envs/benchmark/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/anaconda2/envs/benchmark/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/anaconda2/envs/benchmark/lib/python2.7/site-packages/rio_pansharpen/scripts/cli.py", line 46, in pansharpen
    jobs, half_window, customwindow
  File "/home/ubuntu/anaconda2/envs/benchmark/lib/python2.7/site-packages/rio_pansharpen/worker.py", line 167, in calculate_landsat_pansharpen
    rm.run(jobs)
  File "/home/ubuntu/anaconda2/envs/benchmark/lib/python2.7/site-packages/riomucho/__init__.py", line 108, in run
    with rio.open(self.outpath, 'w', **self.options) as dst:
  File "/home/ubuntu/anaconda2/envs/benchmark/lib/python2.7/site-packages/rasterio/__init__.py", line 193, in open
    s.start()
  File "rasterio/_io.pyx", line 1401, in rasterio._io.RasterUpdater.start (rasterio/_io.c:19697)
ValueError: blockxsize exceeds raster width.
```

**Comment by rafaelalmeida** [comment]
Interestingly enough, the problem may be related to the actual width/height ratio. Just out of curiosity, I tried to make the cropping window perfectly square, and it works fine:

```
gdal_translate -srcwin 3812 2460 740 740 /home/ubuntu/landsat/downloads/LC82220762016210LGN00/LC82220762016210LGN00_B8.TIF gdal_b8.tif

gdal_translate -srcwin 1906 1230 371 371 /home/ubuntu/landsat/downloads/LC82220762016210LGN00/LC82220762016210LGN00_B4.TIF gdal_b4.tif

gdal_translate -srcwin 1906 1230 371 371 /home/ubuntu/landsat/downloads/LC82220762016210LGN00/LC82220762016210LGN00_B3.TIF gdal_b3.tif

gdal_translate -srcwin 1906 1230 371 371 /home/ubuntu/landsat/downloads/LC82220762016210LGN00/LC82220762016210LGN00_B2.TIF gdal_b2.tif
```

**Comment by perrygeo** [comment]
There are some hardcoded [creation options](https://github.com/mapbox/rio-pansharpen/blob/master/rio_pansharpen/worker.py#L135-L137) that effectively prevent users from running this on rasters smaller than 512x512px. This is a bug, I just ran into it today as well. We'll have it fixed in the next release!

**Comment by rafaelalmeida** [comment]
So, as a quick workaround for now, if I can somehow pad my rasters to at least 512 x 512, it should work? Or there are other issues involved?

**Comment by perrygeo** [comment]
I wouldn't advise padding the rasters - that's a pain for what is a simple fix in the code. Basically just remove these three lines: https://github.com/mapbox/rio-pansharpen/blob/master/rio_pansharpen/worker.py#L135-L137 and it should work temporarily until we get out the next release.
