### ISSUE TITLE
Window TypeError

### ISSUE THREAD

**Issue by j08lue** [mapbox/rio-pansharpen#31]
Trying to run this, I am getting the following error, probably because `Window` objects in `rasterio` no longer are tuples.

Rasterio version 1.1.2

```python
MuchoChildError: 
Child process's traceback:
Traceback (most recent call last):
  File "/home/jovyan/.conda/envs/py3/lib/python3.6/site-packages/riomucho/__init__.py", line 63, in wrapper
    return func(*args, **kwds)
  File "/home/jovyan/.conda/envs/py3/lib/python3.6/site-packages/riomucho/__init__.py", line 119, in __call__
    return self.user_func(srcs, window, ij, global_args), window
  File "/home/jovyan/.conda/envs/py3/lib/python3.6/site-packages/rio_pansharpen/worker.py", line 77, in _pansharpen_worker
    rgb_window = _pad_window(rgb_base_window, padding)
  File "/home/jovyan/.conda/envs/py3/lib/python3.6/site-packages/rio_pansharpen/utils.py", line 116, in _pad_window
    (wnd[0][0] - pad, wnd[0][1] + pad),
TypeError: 'Window' object does not support indexing
```

**Comment by j08lue** [comment]
Just noticed that this is already discussed elsewhere (https://github.com/mapbox/rio-pansharpen/pull/29) with an indication that this library is no longer maintained.

**Comment by j08lue** [comment]
Just noticed that this is already discussed elsewhere (https://github.com/mapbox/rio-pansharpen/pull/29) with an indication that this library is no longer maintained.
